In [ ]:
import numpy as np
import pandas as pd
import keras
from keras import layers


num_classes = 6
input_shape = (3,)

df = pd.read_csv("py_data.csv",header=None)

data = df.iloc[:,6:9].to_numpy()
ans = df.iloc[:,5].to_numpy()

#left, right = keras.utils.split_dataset(data, left_size=0.9, shuffle = True)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, ans, test_size=0.20, random_state=33)
#print(left)
#print(data)
#print(ans)
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
print(y_train)

#print(y_train)
print(type(y_train))

[[0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [ ]:
model = keras.Sequential(
    [
        keras.Input(shape=input_shape),
        layers.Dense(10, activation="relu"),
        #layers.Flatten(),
        layers.Dense(num_classes, activation="softmax")
    ]
)

model.summary()
#model.weights


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                40        
                                                                 
 dense_1 (Dense)             (None, 6)                 66        
                                                                 
Total params: 106 (424.00 Byte)
Trainable params: 106 (424.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
batch_size = 100
epochs = 1000

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

Epoch 1/1000
3/3 [==============================] - 1s 178ms/step - loss: 0.1886 - accuracy: 0.9306 - val_loss: 0.3115 - val_accuracy: 0.8750
Epoch 2/1000
3/3 [==============================] - 0s 69ms/step - loss: 0.1667 - accuracy: 0.9769 - val_loss: 0.5465 - val_accuracy: 0.8750
Epoch 3/1000
3/3 [==============================] - 0s 36ms/step - loss: 0.2357 - accuracy: 0.8935 - val_loss: 0.2602 - val_accuracy: 0.8750
Epoch 4/1000
3/3 [==============================] - 0s 36ms/step - loss: 0.0916 - accuracy: 0.9907 - val_loss: 0.2298 - val_accuracy: 0.9167
Epoch 5/1000
3/3 [==============================] - 0s 43ms/step - loss: 0.1120 - accuracy: 0.9491 - val_loss: 0.2296 - val_accuracy: 0.9167
Epoch 6/1000
3/3 [==============================] - 0s 57ms/step - loss: 0.0833 - accuracy: 0.9676 - val_loss: 0.2604 - val_accuracy: 0.9167
Epoch 7/1000
3/3 [==============================] - 0s 55ms/step - loss: 0.0691 - accuracy: 0.9907 - val_loss: 0.2204 - val_accuracy: 0.9167
Epoch 8/1000

In [ ]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])


Test loss: 4.46135709353257e-05
Test accuracy: 1.0


In [ ]:
w1 = model.layers[0].get_weights()[0]
b1  = model.layers[0].get_weights()[1]
w2 = model.layers[1].get_weights()[0]
b2  = model.layers[1].get_weights()[1]

In [ ]:
print("w1:",w1.shape)
print("b1:",b1.shape)
print("w2:",w2.shape)
print("b2:",b2.shape)

w1: (3, 10)
b1: (10,)
w2: (10, 6)
b2: (6,)


In [ ]:
print(y_test[:10])
print(X_test[:10])
model.predict(X_test[:10])


[[0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]
[[1784 1462 1550]
 [1463 1486 1865]
 [1480 1477 1262]
 [1468 1479 1265]
 [1486 1763 1577]
 [1509 1175 1590]
 [1786 1480 1554]
 [1465 1395 1851]
 [1438 1465 1856]
 [1491 1757 1556]]
1/1 [==============================] - 0s 20ms/step


array([[3.2556267e-09, 6.4593912e-16, 9.9999994e-01, 1.6370475e-09,
        0.0000000e+00, 4.7947654e-13],
       [9.9999970e-01, 2.1085616e-07, 0.0000000e+00, 4.6764887e-25,
        0.0000000e+00, 3.0518838e-14],
       [1.6347218e-05, 9.9996477e-01, 1.6070258e-19, 1.3592135e-05,
        1.6969203e-08, 5.3006497e-06],
       [1.2326867e-05, 9.9998349e-01, 6.7290118e-22, 2.3913592e-06,
        2.8738089e-07, 1.5971995e-06],
       [5.6483110e-18, 3.6387305e-06, 0.0000000e+00, 3.3644415e-06,
        9.9999291e-01, 2.3123422e-23],
       [4.1975887e-13, 5.1319178e-14, 4.1489995e-14, 1.6548672e-27,
        0.0000000e+00, 9.9999994e-01],
       [1.1574048e-09, 1.1889746e-16, 9.9999994e-01, 3.7119698e-09,
        0.0000000e+00, 2.0392188e-14],
       [9.9989134e-01, 4.6753874e-05, 0.0000000e+00, 1.6756255e-25,
        0.0000000e+00, 6.1909290e-05],
       [9.9999964e-01, 3.6374766e-07, 0.0000000e+00, 9.8808409e-26,
        0.0000000e+00, 8.6224017e-14],
       [3.3019912e-17, 3.3964068e-06,

In [ ]:
print(b1)
np.savetxt("b1.csv",b1,delimiter =",")
np.savetxt("w1.csv",w1,delimiter =",")
np.savetxt("b2.csv",b2,delimiter =",")
np.savetxt("w2.csv",w2,delimiter =",")
model.save_weights("painot.txt", overwrite=True)



[ 0.          0.         -0.21479212  0.          0.         -0.15974975
  0.01284042 -0.15800238  0.          0.02115146]
